### ISSUE TITLE
这个项目是怎么导入的呀

### ISSUE THREAD

**Issue by tangdu** [chxfantasy/spring-cloud-demo#1]
这个项目是怎么导入的呀

**Comment by chxfantasy** [comment]
mvn项目，导入的话，需要使用maven相关的ide，比如eclipse, idea，我一般使用后者。
整个工程导入的话，可以作为一个整项目导入，也可以将主目录下的所有Project单独导入。

对于项目使用的话，我个人比较建议，每个子project都单独放在一个repo里面，这样在发布、tag、回退的时候不会有发生冲突或者打架
