### ISSUE TITLE
请问我用IDEA如何将这些项目放到一起，这样方便开发，不用在工作空间进行切换？

### ISSUE THREAD

**Issue by AndyLue** [chxfantasy/spring-cloud-demo#3]
<img width="421" alt="qq20180610-105830 2x" src="https://user-images.githubusercontent.com/8328012/41197869-627c67b6-6c9d-11e8-8c8d-24a3ed1062c3.png">
我想要的效果是这样的，请问，你在实际开发中，是一个模块一个工作环境的开发，还是将所有模块放到一起来如上图这样来开发呢？？？

**Comment by chxfantasy** [comment]
你好。
首先开发环境上来讲，你这样开发也没有问题，一个模块一个工作环境也没有问题。我习惯后者。

但是，微服务的目的是为了解耦，解耦是为了方便多人开发。
如果您自己一个人开发的话，就完全没毕业微服务化了，过于麻烦，运维成本也高。
总之，不要为了微服务而微服务。

2018-06-10 11:01 GMT+08:00 Andy <notifications@github.com>:

**Comment by AndyLue** [comment]
3Q

**Comment by carrchen** [comment]
<img width="1440" alt="idea" src="https://user-images.githubusercontent.com/30839621/44980645-0b5d6400-afa3-11e8-8582-f4ff40473371.png">
右侧添加就可以实现
